build_nes:
	ca65 1_4.asm
	ld65 -C nes.cfg 1_4.o -o 1_4.nes

build_nes2:
	ca65 1_2.asm
	ld65 -C nes.cfg 1_2.o -o 1_2.nes

build_nes3:
	ca65 1_3.asm
	ld65 -C nes.cfg 1_3.o -o 1_3.nes

build_nes4:
	ca65 1_4.asm
	ld65 -C nes.cfg 1_4.o -o 1_4.nes

build_nes5:
	ca65 1_5.asm
	ld65 -C nes.cfg 1_5.o -o 1_5.nes

build_nes6:
	ca65 1_6.asm
	ld65 -C nes.cfg 1_6.o -o 1_6.nes

build_nes7:
	ca65 1_7.asm
	ld65 -C nes.cfg 1_7.o -o 1_7.nes

build_nes8:
	ca65 1_8.asm
	ld65 -C nes.cfg 1_8.o -o 1_8.nes

build_nes9:
	ca65 1_9.asm
	ld65 -C nes.cfg 1_9.o -o 1_9.nes

build_blue:
	ca65 blue_fun.asm
	ld65 -C nes.cfg blue_fun.o -o blue_fun.nes